site_name: sing-box-ui
site_description: 人文与自然  #站点描述
site_url: https://example.com  #站点网址 URL，根可位于域名的子目录中
site_author: neo110   #作者
# Repository
repo_name: neo110/sing-box-ui
repo_url: https://github.com/squidfunk/mkdocs-material

# Copyright
copyright: Copyright &copy; 2016 - 2023 neo110

theme:
  name: material
  language: zh
  features:
    - announce.dismiss
    # - content.action.edit
    # - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    # - content.tabs.link
    - content.tooltips
    - header.autohide
    # - navigation.expand
    # - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo


# Plugins
plugins:
  # - blog
  - search:
      lang:   #语言，自动产生最佳结果，不需要设置
        - en  #英语
        - zh  #中文
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true


  # - script:
  #     src: 'js/language-switcher.js'

extra:
  # alternate:
  #   - name: English
  #     link: /
  #     lang: en
  #   - name: 简体中文
  #     link: /zh/
  #     lang: zh
#  version: #版本控制
#    provider: mike
#  homepage: https://example.com  #通常logo链接到主页，这里可修改
  social:  #页脚
    - icon: fontawesome/brands/github   #社交链接
      link: https://twitter.com/squidfunk
      name: squidfunk on Twitter  #一般自动提取
    - icon: fontawesome/solid/envelope  #电子邮件
      link: mailto:neo110@gimail.com
  generator: false  #删除通知“Made with Material for MkDocs”，一般不必
#  analytics: #设置站点分析
#    provider: google
#    property: G-XXXXXXXXXX


# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page tree
nav:
  - 首页: 
    - 简介: 'index.md'
    # - 更新日志: 'changelog.zh.md'
    # - 废弃功能列表: 'deprecated.zh.md'
    - 未来计划: 'roadmap.md'
    - 支持: 'support.md'
  - 下载: 'download.md'
  - 使用: 
    - 安装: 'install.md'
    - 运行: 'runing.md'
    - 免责声明: 'disclaimer.md'
    - 开机自启动: 'autostartserver.md'
    - 守护服务: 'guardserver.md'
    - 修改配置文件: 'config.md'
    - 查看日志: 'viewlog.md'
    - 启动服务: 'startserver.md'
    - 停止服务: 'stopserver.md'
    - 重启服务: 'restartserver.md'
    - 问题:
      - 常见问题: 'faq.md'
      - 问题反馈: 'issue.md'

 
